### ISSUE TITLE
MAX31850 adaptation

### ISSUE THREAD

**Issue by povi2946** [DavidAntliff/esp32-ds18b20#4]
Could we include an adaptation to read MAX31850 devices too?
I believe the only difference is that data is 14-bits resolutions. But in the code there are so many checks to ensure its 9-12.
What would be proper places to change in order to adapt?
Thank you

**Comment by DavidAntliff** [comment]
@povi2946 I don't have one of these devices however I'd be happy to consider a pull request that added support for them. Probably the best way to handle it is an initialisation parameter that selects the type of device, then sets these limits in an internal structure, which the code makes use of elsewhere. If you or someone added support in a PR then I will look at getting a 31850 for myself so that I can test against it.

**Comment by povi2946** [comment]
Actually the current version reads MAX31850 just fine. I believe I had issues with faulty breakout board and then mislabeled thermocouple wires. thanks

**Comment by DavidAntliff** [comment]
Thanks for letting me know. Interesting to hear it works with the MAX31850!
